### ISSUE TITLE
感谢这份开源的oc基础教程！

### ISSUE THREAD

**Issue by hawkinchina** [zonble/kkbox-ios-dev#5]
感谢这份开源的oc基础教程！推荐给大陆的网友阅读，他们反馈一些简体，繁体的术语差异；不好理解，
我在qq群里面，简单做了一个翻译； 考虑到大陆其他网友可能遇到类似的问题，所以这里，提出一个建议；
一些术语（繁体-》简体），简单的翻译和对照，统一给出。
1）檢查某個物件是否實作了某個 method，只要呼叫 respondsToSelector: 就可以了：。 
實作， —〉对应： 实现了。
2）object-c  物件（繁） —》 对应：object-c对象（简）
3）檔案—》 文件。
4）記憶體  —》 内存
5） 型別 —》 类型
6）迴圈 —》 循环
7）指標 —》 指针
8）漏水（Memory Leak）—》 泄漏

**Comment by zonble** [comment]
我把這個對照表放在前言中了，謝謝！

**Comment by hawkinchina** [comment]
看到了，谢谢更新，：）， 期待楼主更加精彩的文章； 用oc陆陆续续开发些应用， 个人一直喜欢c语言，所以对于oc也是格外喜欢， ：） swift前期兼容性问题，故一直未学习，：），近期，主要linux下c开发和研究， 轻车熟路， 内核开源代码， 在内地市场更加普及些，看看oc的在linux的gnustep的项目， 
可以继续使用oc，当然可以使用swfit。。
